# Generated by Django 5.1.6 on 2025-04-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collections',
        ),
    ]