# Generated by Django 5.1.6 on 2025-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcollection',
            name='access',
            field=models.ManyToManyField(related_name='access', to='mainmenu.profile'),
        ),
    ]
