# Generated by Django 5.1.6 on 2025-02-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='user')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('userRole', models.CharField(default='Patron', max_length=200, verbose_name='permission')),
            ],
        ),
    ]
