# Generated by Django 5.1.6 on 2025-03-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0003_class_tag_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='material_type',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='mainmenu.tag'),
        ),
    ]
