# Generated by Django 5.1.6 on 2025-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0004_remove_item_material_type_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='class_obj',
        ),
        migrations.AddField(
            model_name='class',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='classes', to='mainmenu.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='mainmenu.tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pics/'),
        ),
    ]
