# Generated by Django 5.1.6 on 2025-03-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0005_remove_tag_class_obj_class_items_alter_item_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='items',
        ),
        migrations.AddField(
            model_name='class',
            name='required_tags',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='mainmenu.tag'),
        ),
    ]
