# Generated by Django 5.1.6 on 2025-03-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0005_alter_profile_profile_picture'),
        ('mainmenu', '0006_remove_class_items_class_required_tags'),
    ]

    operations = [
    ]
