# Generated by Django 5.1.6 on 2025-04-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0005_alter_profile_profile_picture_collections'),
        ('mainmenu', '0007_merge_20250330_2334'),
    ]

    operations = [
    ]
