# Generated by Django 5.1.6 on 2025-04-10 02:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0007_merge_20250330_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='identifier',
            new_name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. home library, work library', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('in_circulation', 'In Circulation'), ('repairing', 'Being Repaired'), ('lost', 'Lost')], default='checked_in', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='items', to='mainmenu.collection'),
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='items', to='mainmenu.itemimage'),
        ),
    ]
