# Generated by Django 5.1.6 on 2025-04-10 02:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0008_collection_itemimage_rename_identifier_item_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
