# Generated by Django 5.1.6 on 2025-04-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0008_merge_20250411_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
    ]
