# Generated by Django 5.1.6 on 2025-04-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0009_alter_item_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_circulation', 'In Circulation'), ('repairing', 'Being Repaired'), ('lost', 'Lost')], default='available', max_length=20),
        ),
    ]
