# Generated by Django 5.1.6 on 2025-04-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0010_alter_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
    ]
