# Generated by Django 5.1.6 on 2025-04-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0009_alter_item_identifier'),
        ('mainmenu', '0011_remove_item_is_available'),
    ]

    operations = [
    ]
