# Generated by Django 5.1.6 on 2025-04-14 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0013_item_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='collections',
        ),
        migrations.AddField(
            model_name='collection',
            name='access',
            field=models.ManyToManyField(related_name='access', to='mainmenu.profile'),
        ),
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='mainmenu.profile'),
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(related_name='collections_of', to='mainmenu.item'),
        ),
        migrations.AddField(
            model_name='collection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public'),
        ),
    ]
